openapi: '3.0.3'

info:
  title: "Alyce Public API"
  description: "We will add more details later before publishing the V1 version of our API"
  contact:
    name: Alyce
    email: support@alyce.com
    url: https://alyce.com
  version: '0.1.0'

servers:
  - url: https://api.alyce.com
    description: Entrypoint for API calls

tags:
  - name: Contacts
    description: |
      All endpoints related to contacts
  - name: Reporting
    description: |
      Endpoints to get the needed reports via API

paths:
  /v1/reporting/gifts:
    $ref: 'reporting/paths.yaml#/getGiftInvitationReport'
  /v1/contacts:
    $ref: 'contacts/paths.yaml#/contacts'
  /v1/contacts/{contactId}:
    $ref: 'contacts/paths.yaml#/contact'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
